import Head from 'next/head'
import Image from 'next/image'
import Banner from '../component/Banner/Banner'
import FirstSection from '../component/FirstSection/FirstSection'
import Navbar from '../component/Navbar/Navbar'
import SecondSection from '../component/SecondSection/SecondSection'
import ThirdSection from '../component/ThirdSection/ThirdSection'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#03142D]'>
        <Navbar/>
        <Banner/>
        <FirstSection/>
        <SecondSection/>
        <ThirdSection/>
      </div>
        <p className='text-red-500'>Test.................</p>
        <h1 className='bg-red-600'>Habib</h1>
        <img src="/download.jpg" alt="" />
    </div>
  )
}
